export const DEFAULT_TRANSCRIPTION_PROVIDER = 'local_sensevoice'
export const DEFAULT_LOCAL_TRANSCRIPTION_MODEL_ID = 'iic/SenseVoiceSmall'
export const DEFAULT_LOCAL_TRANSCRIPTION_DEVICE = 'cuda:0'
export const DEFAULT_LOCAL_TRANSCRIPTION_LANGUAGE = 'zh'
export const DEFAULT_RESOURCE_MODE = 'balanced'
